import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <ul>
          <li><a href="/">ホーム</a></li>
          <li><a href="/form">入力フォーム</a></li>
        </ul>
        {children}
      </body>
    </html>
  );
}
