spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:develop;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      pool-name: ConnectionPool
      leakDetectionThreshold: 5000
      maximum-pool-size: 20
      minimum-idle: 10
      username: sa
      password:
      driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations:
        - classpath:h2/schema.sql
      mode: embedded # (DB????SQL????)????.EMBEDDED=h2db???????. ALWAYS????